spring:
  data:
    rest:
      default-page-size: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      path: /h2-console
      enabled: true

springdoc:
  swagger-ui:
    path: /api/docs

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG