spring:
  datasource:
    url: jdbc:h2:mem:db;Mode=Oracle
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  mvc:
    log-request-details: true

frontend-url: localhost:4200

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG