spring:
  data:
    rest:
      default-page-size: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    log-request-details: true
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
#    url: jdbc:postgresql://localhost:5432/db
#    username: postgres
#    password: postgres
    url: jdbc:h2:mem:db;Mode=Oracle
    username: sa
    password: password
    driver-class-name: org.h2.Driver


springdoc:
  swagger-ui:
    path: /api/docs

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG