version: "3.9"
services:
  frontend:
    image: youlx/frontend
    build: frontend
    ports:
      - 8080:8080
    environment:
      HEROKU_APP_BACKEND_URL: backend:8081
      PORT: 8080
    links:
      - "backend:backend"
  backend:
    image: youlx/backend
    build: backend
    ports:
      - 8081:8080
    environment:
      PORT: 8081
      HEROKU_APP_FRONTEND_URL: frontend:8080
      HATEOAS_CALLBACK_URL: ""
      DATABASE_URL: db:5432
  db:
    image: postgres:14.5-alpine3.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - lx_postgres:/var/lib/postgresql/data

volumes:
  lx_postgres:
    driver: local