version: "3.8"
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - lx_postgres:/var/lib/postgresql/data
volumes:
  lx_postgres:
    driver: local
