server:
  port: 8080

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:db;Mode=Oracle
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        format_sql=true:
  data:
    rest:
      default-page-size: 10

springdoc:
  swagger-ui:
    path: /api/docs

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

hashids:
  salt: DefaultSaltWhoCares