name: CI/CD

on: push

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true
      - name: tests
        working-directory: ./frontend
        run: |
          pnpm run test
      - name: build
        working-directory: ./frontend
        run: |
          pnpm run build

  backend-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 18
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
        arguments: build
        build-root-directory: ./backend

  frontend-deploy:
    needs: frontend-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_FRONTEND }}
          dockerfile_directory: ./frontend
          dockerfile_name: Dockerfile
          process_type: web

  backend-deploy:
    needs: backend-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_BACKEND }}
          dockerfile_directory: ./backend
          dockerfile_name: Dockerfile
          process_type: web